# Generated by Django 3.0.4 on 2020-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educApp', '0002_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='object_id',
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
