# Generated by Django 3.0.4 on 2020-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educApp', '0003_auto_20200604_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
